### ISSUE TITLE
error in administration 

### ISSUE THREAD

**Issue by markosc** [tad0616/tad_player#9]
http://localhost/web/modules/tad_player/admin/main.php
![2019-06-18_02-53-40](https://user-images.githubusercontent.com/16872280/59663289-53d1c100-9174-11e9-81bd-5c30347b44bd.jpg)

Error : Error: Class 'XoopsModules\Tadtools\Utility' not found

http://localhost/web/modules/tad_player/admin/main.php?op=mk_all_xml
Error : Error: Class 'XoopsModules\Tadtools\Utility' not found

XOOPS 2.5.10 PHP 7.1.8 MYSQL 5.6.37
tadtools and tad_player , last of github :(

**Comment by mambax7** [comment]
Do you have the latest Tadtools installed? 
https://github.com/tad0616/tadtools

**Comment by markosc** [comment]
Yes, i downloaded it today, I also have rmcommon I don't know if that also influences

**Comment by markosc** [comment]
> Do you have the latest Tadtools installed?
> https://github.com/tad0616/tadtools

yes, it is solved by uninstalling rmcommon, but I use mywords and qpages :/

**Comment by mambax7** [comment]
Hmm, interesting. It should not have any impact. 
Try to install now again rmcommon and see if there is still a problem. 
I'll try to install both this weekend and see what is happening.
Thanks for reporting it.

**Comment by markosc** [comment]
> Hmm, interesting. It should not have any impact.
> Try to install now again rmcommon and see if there is still a problem.
> I'll try to install both this weekend and see what is happening.
> Thanks for reporting it.

I downloaded the fork of rmcommon, xthemes, mywords from your directories and I had no problem, I will try to update everything. thank you and I close the subject thank you.
